/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
bool yyfrom_FILE=true;
int    yy_FILE_string_pos = 0;
char * yy_FILE_string = NULL;
FILE * yy_FILE_file = 0;
char get_char(void)
{
	if (yy_FILE_string[yy_FILE_string_pos] == 0) {
		return EOF;
	}
	else {
		yy_FILE_string_pos++;
		return yy_FILE_string[yy_FILE_string_pos-1];
	}
}

char unget_char() {
	if (yy_FILE_string_pos != 0) {
		yy_FILE_string_pos--;
		return yy_FILE_string[yy_FILE_string_pos];
	}
	else return EOF;
}

int getcharf(void) {
	if (yyfrom_FILE == true) {
		if (yy_FILE_file == NULL) yy_FILE_file = stdin;
		return getc(yy_FILE_file);
	}
	else return get_char();
}
int ungetcf(int c) {
	if (yyfrom_FILE == true) {
		if (yy_FILE_file == NULL) yy_FILE_file = stdin;
		return ungetc(c, yy_FILE_file);
	}
	else return unget_char();
}

#define YYRULECOUNT 24

#include <stdio.h>
#include "../Shell/builtins/env.h"
#include "../Shell/builtins/printfmacro.h"
#include "../Shell/builtins/clock.h"
	char * __ISA_FUNCTION__ = NULL;
	#define ISA_FUNC_ASSIGN if (__ISA_FUNCTION__) { free(__ISA_FUNCTION__); __ISA_FUNCTION__ = NULL; } __ISA_FUNCTION__ = strdup(yytext)

#ifndef REGEX_STR
int getbitgroupcount(int bit) {
	return snprintf(stdout, 0, "%d", bit);
}

struct regex_string_structure
{
	char * string;
	int index;
	int len;
	int malloced;
};

struct regex_string
{
	char * string;
	struct regex_string_structure escaped;
	struct regex_string_structure json;
	struct regex_string_structure c_define;
	int index;
	int len;
	int malloced;
};

#define str_malloc_(y, z) \
	y.string = malloc(z); \
	memset(y.string, 0, z); \
	y.malloced = z; \
	y.len = 0; \
	y.index = 0;

#define str_mallocr(y, z) \
	str_malloc_(y, z); \
	str_malloc_(y.escaped, z); \
	str_malloc_(y.json, z); \
	str_malloc_(y.c_define, z); \
	
#define str_malloc(y, z) \
	struct regex_string y; \
	str_mallocr(y, z);

#define str_new(str) \
	str_malloc(str, 1) \
	
#define str_free_(y) \
		memset(y.string, 0, y.malloced); \
		free(y.string); \
		y.string = NULL; \
		y.malloced = 0; \
		y.len = 0; \
		y.index = 0; \

#define str_free(y) \
	{ \
		str_free_(y); \
		str_free_(y.escaped); \
		str_free_(y.json); \
		str_free_(y.c_define); \
	}
	
#define str_reset_(str) { \
	str_free_(str) \
	str_malloc_(str, 1) \
}

#define str_reset(str) { \
	str_reset_(str) \
	str_reset_(str.escaped) \
	str_reset_(str.json) \
	str_reset_(str.c_define) \
}

#define str_realloc(y, z) \
	y.string = realloc(y.string, z); \
	if (y.malloced < z) { \
		memset(y.string+y.malloced, 0, y.malloced-z); \
	} \
	y.malloced = z;
	
#define str_info_(str) \
		printf("%s.index = %d\n", #str, str.index); \
		printf("%s.len = %d\n", #str, str.len); \
		printf("%s.malloced = %d\n", #str, str.malloced); \
		printf("%s.string = %s\n", #str, str.string); \

#define str_info(str) { \
	str_info_(str) \
	str_info_(str.escaped) \
	str_info_(str.json) \
	str_info_(str.c_define) \
}

#define str_insert_char(str, ch) { \
	str_realloc(str, str.malloced+2); \
	str.string[str.index] = ch; \
	str.index++; \
	str.string[str.index] = 0; \
	str.len = strlen(str.string); \
}

#define str_undo(str) { \
	str.index--; \
	str.string[str.index] = 0; \
	str_realloc(str, str.malloced-1); \
	str.len = strlen(str.string); \
}

#define rng(s, e) ( uch >= s && uch <= e)

#define str_insert_string(str, string) { \
	const unsigned char * s = string; \
	const unsigned int size = strlen(string); \
	int c; \
	unsigned char uch; \
	str_insert_char(str.c_define, '#') \
	str_insert_char(str.c_define, 'd') \
	str_insert_char(str.c_define, 'e') \
	str_insert_char(str.c_define, 'f') \
	str_insert_char(str.c_define, 'i') \
	str_insert_char(str.c_define, 'n') \
	str_insert_char(str.c_define, 'e') \
	str_insert_char(str.c_define, ' ') \
	int i; \
	for (i = 0; i < size; ++i) { \
		c = s[i]; \
		uch = (unsigned char) s[i]; \
		str_insert_char(str, c); \
		\
		/* escape sequences under gnu gcc are interperated by both cc1, and the terminal, assembling a string containing an invalid sequence will print as if it does not have the \ before it*/ \
		\
		if (isalnum(c) ) { \
			str_insert_char(str.c_define, c); \
		} \
		else str_insert_char(str.c_define, '_'); \
		if (c == '\a') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 'a'); \
		} \
		else if (c == '\b') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 'b'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, 'b'); \
		} \
		else if (c == '\f') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 'f'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, 'f'); \
		} \
		else if (c == '\n') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 'n'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, 'n'); \
		} \
		else if (c == '\r') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 'r'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, 'r'); \
		} \
		else if (c == '\t') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 't'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, 't'); \
		} \
		else if (c == '\v') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, 'v'); \
		} \
		else if (c == '\\') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, '\\'); \
		} \
		else if (c == '\'') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, '\''); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, '\''); \
		} \
		else if (c == '"') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, '"'); \
			str_insert_char(str.json, '\\'); \
			str_insert_char(str.json, '"'); \
		} \
		else if (c == '\?') { \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, '?'); \
		} \
		else if (c >= ' ' && c <= 0x7e) { \
			str_insert_char(str.escaped, c); \
			str_insert_char(str.json, c); \
		} \
		else if (c >= '0' && c <= '9' ) { \
			/* Print \ooo */ \
			str_insert_char(str.escaped, '\\'); \
			str_insert_char(str.escaped, '0' + (c >> 6)); \
			str_insert_char(str.escaped, '0' + ((c >> 3) & 0x7)); \
			str_insert_char(str.escaped, '0' + (c & 0x7)); \
		} else { \
			/* Print \[[o]o]o */ \
			str_insert_char(str.escaped, '\\'); \
			if ((c >> 3) != 0) { \
				if ((c >> 6) != 0) str_insert_char(str.escaped, '0' + (c >> 6)); \
				str_insert_char(str.escaped, '0' + ((c >> 3) & 0x7)); \
			} \
			str_insert_char(str.escaped, '0' + (c & 0x7)); \
		} \
	} \
	str_insert_char(str.c_define, '\n'); \
}

#define str_int2string(x,y) \
	char * x = malloc(getbitgroupcount(y)); \
	sprintf(x, "%d", y);
	
#define str_insert_int(str, integer) { \
	str_int2string(j, integer); \
	str_insert_string(str, j); \
	free(j); \
}

int reverseBool(int val) {
	if (val == 1 || val == 0) return val^1;
	else return val;
}

void str_output(struct regex_string * str, const char * file);

void str_output_append(struct regex_string * str, const char * file);

#define str_output(str, file) { \
	FILE * stream = stdout; \
	int isfile = 0; \
	if (strcmp("stdin" file) == 0) stream = stdin; \
	else if(strcmp("stdout" file) == 0) stream = stdout; \
	else if(strcmp("stderr" file) == 0) stream = stderr; \
	else isfile = 1; \
	if (isfile) stream = fopen(file, "w"); \
	fwrite(str.string,str.len, 1, stream); \
	if (isfile) fclose(stream); \
}

#define str_output_append(str, file) { \
	FILE * stream = stdout; \
	int isfile = 0; \
	if (strcmp("stdin" file) == 0) stream = stdin; \
	else if(strcmp("stdout" file) == 0) stream = stdout; \
	else if(strcmp("stderr" file) == 0) stream = stderr; \
	else isfile = 1; \
	if (isfile) stream = fopen(file, "a"); \
	fwrite(str.string,str.len, 1, stream); \
	if (isfile) fclose(stream); \
}
#endif
#ifndef REGEX_PCR
#define PCRE2_CODE_UNIT_WIDTH 8

#include <stdio.h>
#include <string.h>
#include <pcre2.h>
#include <stdbool.h>

int regex(char * RegexStr, char * source)
{
	bool Found = false;
	pcre2_code *re;
	PCRE2_SPTR pattern;
	PCRE2_SPTR subject;
	int errornumber;
	int rc;
	PCRE2_SIZE erroroffset;
	PCRE2_SIZE *ovector;
	size_t subject_length;
	pcre2_match_data *match_data;
	
	pattern = (PCRE2_SPTR)RegexStr;// <<<<< This is where you pass your REGEX 
	subject = (PCRE2_SPTR)source;// <<<<< This is where you pass your bufer that will be checked. 
	subject_length = strlen((char *)subject);
	re = pcre2_compile (
	  pattern,               /* the pattern */
	  PCRE2_ZERO_TERMINATED, /* indicates pattern is zero-terminated */
	  0,                     /* default options */
	  &errornumber,          /* for error number */
	  &erroroffset,          /* for error offset */
	  NULL);                 /* use default compile context */
	
	/* Compilation failed: print the error message and exit. */
	if (re == NULL)
	{
	  PCRE2_UCHAR buffer[256];
	  pcre2_get_error_message(errornumber, buffer, sizeof(buffer));
	  printf("PCRE2 compilation failed at offset %d: %s\n", (int)erroroffset,buffer);
	  return 1;
	}
	
	
	match_data = pcre2_match_data_create_from_pattern(re, NULL);
	
	rc = pcre2_match(
	  re,
	  subject,              /* the subject string */
	  subject_length,       /* the length of the subject */
	  0,                    /* start at offset 0 in the subject */
	  0,                    /* default options */
	  match_data,           /* block for storing the result */
	  NULL);
  PCRE2_UCHAR ** list = NULL;
  PCRE2_SIZE * listlen = NULL;
  int rc2 = pcre2_substring_list_get(match_data, &list, &listlen);
  if(rc2 >=0  && rc >=0) {
    for (int i = 0; list[i]; i++) {
      printf("list[%d] = %s\n", i, list[i]);
      }
    }
  pcre2_match_data_free(match_data);   /* Release memory used for the match */
 	pcre2_code_free(re);
	return rc;
}

/* Author: mgood7123 (Matthew James Good) http://github.com/mgood7123 */
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

struct matched {
  char * match;
  int len;
  int start;
  int size;
};

#define matched_malloc_(y, z) { \
	y = malloc(sizeof(struct matched)*(z)); \
	memset(y, 0, sizeof(struct matched)*(z)); \
	y->size = (z); \
}

#define matched_malloc(y, z) \
	struct matched * y; \
	matched_malloc_(y, z);

#define matched_new(match) \
	matched_malloc(match, 1)

#define matched_free(y) { \
    for (int i = 0; i < y->size; i++) { \
      free(y[i].match); \
      y[i].len = 0; \
      y[i].start = 0; \
    }\
    y->size = 0; \
    free(y); \
}

#define matched_reset(match) { \
	matched_free(match) \
	matched_malloc_(match, 1) \
}

#define matched_realloc(y, z) { \
	y = realloc(y, sizeof(struct matched)*(z)); \
	if (y->size < sizeof(struct matched)*(z)) { \
		memset(y+y->size, 0, sizeof(struct matched)); \
	} \
	y->size = (z); \
}

#define matched_add(matched_match, matched_string, matched_len, matched_start) { \
  int matched_index = 0; \
	if (matched_match->match) { \
    matched_realloc(matched_match, matched_match->size+1); \
    matched_index = matched_match->size-1; \
  } \
	matched_match[matched_index].match = matched_string; \
	matched_match[matched_index].start = matched_start; \
	matched_match[matched_index].len = matched_len; \
}

#define matched_info_(matched_match, matched_i) { \
		printf("%s[%d].match = %s\n", #matched_match, matched_i, matched_match[i].match); \
		printf("%s[%d].len = %d\n", #matched_match, matched_i, matched_match[i].len); \
		printf("%s[%d].start = %d\n\n", #matched_match, matched_i, matched_match[i].start); \
}

#define matched_info(matched_match) { \
		printf("number of indexes in %s = %d\n", #matched_match, matched_match->size); \
		for (int i = 0; i < matched_match->size; i++) { \
      matched_info_(matched_match, i); \
    } \
}

int get_lines(char * file) {
  int p = 0, lines = 0;
  while(file[p]) {
    if(file[p] == '\n') lines++;
    p++;
  }
  if (lines == 0) lines = 1;
  return lines;
}

struct regex_string get_upto_x_lines(int line, char * file) {
  str_new(f);
  int p = 0, lines = 0, lines_total = 0, dest_line = 0;
  while(file[p]) {
    if (line == lines_total) dest_line = 1;
    str_insert_char(f, file[p]);
    if(file[p+1] == '\n') {
      if (dest_line) return f;
      lines++;
    }
    p++;
  }
  return f;
}

int calculate_correct_line_from_column(int column, char * file) {
  int p = 0, lines = 0, columns_total = 0;
  while(file[p]) {
    if(file[p] == '\n') {
      lines++;
    }
    columns_total++;
    if (column == columns_total) return lines;
    p++;
  }
  return -1;
}


int calculate_correct_column(int column, char * file) {
  int p = 0, lines = 0, columns = 0, columns_total = 0;
  while(file[p]) {
    columns++;
    if(file[p] == '\n') {
      lines++;
      columns = 0;
    }
    columns_total++;
    if (column == columns_total) return columns;
    p++;
  }
  return -1;
}



// pcre2demo man page

// Return to the PCRE2 index page.

// This page is part of the PCRE2 HTML documentation. It was generated automatically from the original man page. If there is any nonsense in it, please consult the man page, in case the conversion went wrong.

/*************************************************
*           PCRE2 DEMONSTRATION PROGRAM          *
*************************************************/

/* This is a demonstration program to illustrate a straightforward way of
using the PCRE2 regular expression library from a C program. See the
pcre2sample documentation for a short discussion ("man pcre2sample" if you have
the PCRE2 man pages installed). PCRE2 is a revised API for the library, and is
incompatible with the original PCRE API.

There are actually three libraries, each supporting a different code unit
width. This demonstration program uses the 8-bit library. The default is to
process each code unit as a separate character, but if the pattern begins with
"(*UTF)", both it and the subject are treated as UTF-8 strings, where
characters may occupy multiple code units.

In Unix-like environments, if PCRE2 is installed in your standard system
libraries, you should be able to compile this program using this command:

cc -Wall pcre2demo.c -lpcre2-8 -o pcre2demo

If PCRE2 is not installed in a standard place, it is likely to be installed
with support for the pkg-config mechanism. If you have pkg-config, you can
compile this program using this command:

cc -Wall pcre2demo.c `pkg-config --cflags --libs libpcre2-8` -o pcre2demo

If you do not have pkg-config, you may have to use something like this:

cc -Wall pcre2demo.c -I/usr/local/include -L/usr/local/lib \
  -R/usr/local/lib -lpcre2-8 -o pcre2demo

Replace "/usr/local/include" and "/usr/local/lib" with wherever the include and
library files for PCRE2 are installed on your system. Only some operating
systems (Solaris is one) use the -R option.

Building under Windows:

If you want to statically link this program against a non-dll .a file, you must
define PCRE2_STATIC before including pcre2.h, so in this environment, uncomment
the following line. */

/* #define PCRE2_STATIC */

/* The PCRE2_CODE_UNIT_WIDTH macro must be defined before including pcre2.h.
For a program that uses only one code unit width, setting it to 8, 16, or 32
makes it possible to use generic function names such as pcre2_compile(). Note
that just changing 8 to 16 (for example) is not sufficient to convert this
program to process 16-bit characters. Even in a fully 16-bit environment, where
string-handling functions such as strcmp() and printf() work with 16-bit
characters, the code for handling the table of named substrings will still need
to be modified. */

/**************************************************************************
* Here is the program. The API includes the concept of "contexts" for     *
* setting up unusual interface requirements for compiling and matching,   *
* such as custom memory managers and non-standard newline definitions.    *
* This program does not do any of this, so it makes no use of contexts,   *
* always passing NULL where a context could be given.                     *
**************************************************************************/

int regex_verbose2(PCRE2_SPTR pattern, PCRE2_SPTR subject, int find_all, struct matched ** m, bool verbose)
{
pcre2_code *re;
/* PCRE2_SPTR is a pointer to unsigned code units of */
/* the appropriate width (in this case, 8 bits). */
PCRE2_SPTR name_table;

int crlf_is_newline;
int errornumber;
int i;
int rc;
int utf8;

uint32_t option_bits;
uint32_t namecount;
uint32_t name_entry_size;
uint32_t newline;

PCRE2_SIZE erroroffset;
PCRE2_SIZE *ovector;

size_t subject_length;
pcre2_match_data *match_data;

str_new(f);
int column;
int line;




/**************************************************************************
* First, sort out the command line. There is only one possible option at  *
* the moment, "-g" to request repeated matching to find all occurrences,  *
* like Perl's /g option. We set the variable find_all to a non-zero value *
* if the -g option is present.                                            *
**************************************************************************/

/* After the options, we require exactly two arguments, which are the pattern,
and the subject string. */

/* As pattern and subject are char arguments, they can be straightforwardly
cast to PCRE2_SPTR as we are working in 8-bit code units. */

subject_length = strlen((char *)subject);


/*************************************************************************
* Now we are going to compile the regular expression pattern, and handle *
* any errors that are detected.                                          *
*************************************************************************/

re = pcre2_compile(
  pattern,               /* the pattern */
  PCRE2_ZERO_TERMINATED, /* indicates pattern is zero-terminated */
  0,                     /* default options */
  &errornumber,          /* for error number */
  &erroroffset,          /* for error offset */
  NULL);                 /* use default compile context */

/* Compilation failed: print the error message and exit. */

if (re == NULL)
  {
  PCRE2_UCHAR buffer[256];
  pcre2_get_error_message(errornumber, buffer, sizeof(buffer));
  if (verbose == true) printf("PCRE2 compilation failed at offset %d: %s\n", (int)erroroffset,
    buffer);
  return 1;
  }


/*************************************************************************
* If the compilation succeeded, we call PCRE again, in order to do a     *
* pattern match against the subject string. This does just ONE match. If *
* further matching is needed, it will be done below. Before running the  *
* match we must set up a match_data block for holding the result.        *
*************************************************************************/

/* Using this function ensures that the block is exactly the right size for
the number of capturing parentheses in the pattern. */

match_data = pcre2_match_data_create_from_pattern(re, NULL);

rc = pcre2_match(
  re,                   /* the compiled pattern */
  subject,              /* the subject string */
  subject_length,       /* the length of the subject */
  0,                    /* start at offset 0 in the subject */
  0,                    /* default options */
  match_data,           /* block for storing the result */
  NULL);                /* use default match context */

/* Matching failed: handle error cases */

if (rc < 0)
  {
  if (verbose == true) switch(rc)
    {
    case PCRE2_ERROR_NOMATCH: printf("No match\n"); break;
    /*
    Handle other special cases if you like
    */
    default: printf("Matching error %d\n", rc); break;
    }
  pcre2_match_data_free(match_data);   /* Release memory used for the match */
  pcre2_code_free(re);                 /* data and the compiled pattern. */
  return 1;
  }

/* Match succeeded. Get a pointer to the output vector, where string offsets are
stored. */
ovector = pcre2_get_ovector_pointer(match_data);
if (!m) {
  column = calculate_correct_column((int)ovector[0]+1, subject);
  line = calculate_correct_line_from_column((int)ovector[0]+1, subject);
  f = get_upto_x_lines(line, subject);
  if (verbose == true) printf("Match succeeded at offset %d\n", (int)ovector[0]);
  if (verbose == true) printf("%s\n%*c\n", f.string, column, '^');
  str_reset(f);
}
/*************************************************************************
* We have found the first match within the subject string. If the output *
* vector wasn't big enough, say so. Then output any substrings that were *
* captured.                                                              *
*************************************************************************/

/* The output vector wasn't big enough. This should not happen, because we used
pcre2_match_data_create_from_pattern() above. */

if (rc == 0)
  if (verbose == true) printf("ovector was not big enough for all the captured substrings\n");

/* We must guard against patterns such as /(?=.\K)/ that use \K in an assertion
to set the start of a match later than its end. In this demonstration program,
we just detect this case and give up. */

if (ovector[0] > ovector[1])
  {
  if (verbose == true) printf("\\K was used in an assertion to set the match start after its end.\n"
    "From end to start the match was: %.*s\n", (int)(ovector[0] - ovector[1]),
      (char *)(subject + ovector[1]));
  if (verbose == true) printf("Run abandoned\n");
  pcre2_match_data_free(match_data);
  pcre2_code_free(re);
  str_free(f);
  return 1;
  }

/* Show substrings stored in the output vector by number. Obviously, in a real
application you might want to do things other than print them. */

for (i = 0; i < rc; i++)
  {
  PCRE2_SPTR substring_start = subject + ovector[2*i];
  size_t substring_length = ovector[2*i+1] - ovector[2*i];
  if (m) {
    str_new(match);
    for (int ii = 0; ii < (int)substring_length; ii++)
      str_insert_char(match, substring_start[ii]);
    matched_add((*m), strdup(match.string), (int)substring_length, ovector[2*i]);
    str_free(match);
  } else if (verbose == true) printf("%2d: %.*s\n", i, (int)substring_length, (char *)substring_start);
  }


/**************************************************************************
* That concludes the basic part of this demonstration program. We have    *
* compiled a pattern, and performed a single match. The code that follows *
* shows first how to access named substrings, and then how to code for    *
* repeated matches on the same subject.                                   *
**************************************************************************/

/* See if there are any named substrings, and if so, show them by name. First
we have to extract the count of named parentheses from the pattern. */

(void)pcre2_pattern_info(
  re,                   /* the compiled pattern */
  PCRE2_INFO_NAMECOUNT, /* get the number of named substrings */
  &namecount);          /* where to put the answer */

if (namecount != 0)
  {
  PCRE2_SPTR tabptr;
  if (verbose == true) printf("Named substrings\n");

  /* Before we can access the substrings, we must extract the table for
  translating names to numbers, and the size of each entry in the table. */

  (void)pcre2_pattern_info(
    re,                       /* the compiled pattern */
    PCRE2_INFO_NAMETABLE,     /* address of the table */
    &name_table);             /* where to put the answer */

  (void)pcre2_pattern_info(
    re,                       /* the compiled pattern */
    PCRE2_INFO_NAMEENTRYSIZE, /* size of each entry in the table */
    &name_entry_size);        /* where to put the answer */

  /* Now we can scan the table and, for each entry, print the number, the name,
  and the substring itself. In the 8-bit library the number is held in two
  bytes, most significant first. */

  tabptr = name_table;
  for (i = 0; i < namecount; i++)
    {
    int n = (tabptr[0] << 8) | tabptr[1];
    if (verbose == true) printf("(%d) %*s: %.*s\n", n, name_entry_size - 3, tabptr + 2,
      (int)(ovector[2*n+1] - ovector[2*n]), subject + ovector[2*n]);
    tabptr += name_entry_size;
    }
  }


/*************************************************************************
* If the "-g" option was given on the command line, we want to continue  *
* to search for additional matches in the subject string, in a similar   *
* way to the /g option in Perl. This turns out to be trickier than you   *
* might think because of the possibility of matching an empty string.    *
* What happens is as follows:                                            *
*                                                                        *
* If the previous match was NOT for an empty string, we can just start   *
* the next match at the end of the previous one.                         *
*                                                                        *
* If the previous match WAS for an empty string, we can't do that, as it *
* would lead to an infinite loop. Instead, a call of pcre2_match() is    *
* made with the PCRE2_NOTEMPTY_ATSTART and PCRE2_ANCHORED flags set. The *
* first of these tells PCRE2 that an empty string at the start of the    *
* subject is not a valid match; other possibilities must be tried. The   *
* second flag restricts PCRE2 to one match attempt at the initial string *
* position. If this match succeeds, an alternative to the empty string   *
* match has been found, and we can print it and proceed round the loop,  *
* advancing by the length of whatever was found. If this match does not  *
* succeed, we still stay in the loop, advancing by just one character.   *
* In UTF-8 mode, which can be set by (*UTF) in the pattern, this may be  *
* more than one byte.                                                    *
*                                                                        *
* However, there is a complication concerned with newlines. When the     *
* newline convention is such that CRLF is a valid newline, we must       *
* advance by two characters rather than one. The newline convention can  *
* be set in the regex by (*CR), etc.; if not, we must find the default.  *
*************************************************************************/

if (!find_all)     /* Check for -g */
  {
  pcre2_match_data_free(match_data);  /* Release the memory that was used */
  pcre2_code_free(re);                /* for the match data and the pattern. */
  str_free(f);
  return 0;                           /* Exit the program. */
  }

/* Before running the loop, check for UTF-8 and whether CRLF is a valid newline
sequence. First, find the options with which the regex was compiled and extract
the UTF state. */

(void)pcre2_pattern_info(re, PCRE2_INFO_ALLOPTIONS, &option_bits);
utf8 = (option_bits & PCRE2_UTF) != 0;

/* Now find the newline convention and see whether CRLF is a valid newline
sequence. */

(void)pcre2_pattern_info(re, PCRE2_INFO_NEWLINE, &newline);
crlf_is_newline = newline == PCRE2_NEWLINE_ANY ||
                  newline == PCRE2_NEWLINE_CRLF ||
                  newline == PCRE2_NEWLINE_ANYCRLF;

/* Loop for second and subsequent matches */

for (;;)
  {
  uint32_t options = 0;                   /* Normally no options */
  PCRE2_SIZE start_offset = ovector[1];   /* Start at end of previous match */

  /* If the previous match was for an empty string, we are finished if we are
  at the end of the subject. Otherwise, arrange to run another match at the
  same point to see if a non-empty match can be found. */

  if (ovector[0] == ovector[1])
    {
    if (ovector[0] == subject_length) break;
    options = PCRE2_NOTEMPTY_ATSTART | PCRE2_ANCHORED;
    }

  /* If the previous match was not an empty string, there is one tricky case to
  consider. If a pattern contains \K within a lookbehind assertion at the
  start, the end of the matched string can be at the offset where the match
  started. Without special action, this leads to a loop that keeps on matching
  the same substring. We must detect this case and arrange to move the start on
  by one character. The pcre2_get_startchar() function returns the starting
  offset that was passed to pcre2_match(). */

  else
    {
    PCRE2_SIZE startchar = pcre2_get_startchar(match_data);
    if (start_offset <= startchar)
      {
      if (startchar >= subject_length) break;   /* Reached end of subject.   */
      start_offset = startchar + 1;             /* Advance by one character. */
      if (utf8)                                 /* If UTF-8, it may be more  */
        {                                       /*   than one code unit.     */
        for (; start_offset < subject_length; start_offset++)
          if ((subject[start_offset] & 0xc0) != 0x80) break;
        }
      }
    }

  /* Run the next matching operation */

  rc = pcre2_match(
    re,                   /* the compiled pattern */
    subject,              /* the subject string */
    subject_length,       /* the length of the subject */
    start_offset,         /* starting offset in the subject */
    options,              /* options */
    match_data,           /* block for storing the result */
    NULL);                /* use default match context */

  /* This time, a result of NOMATCH isn't an error. If the value in "options"
  is zero, it just means we have found all possible matches, so the loop ends.
  Otherwise, it means we have failed to find a non-empty-string match at a
  point where there was a previous empty-string match. In this case, we do what
  Perl does: advance the matching position by one character, and continue. We
  do this by setting the "end of previous match" offset, because that is picked
  up at the top of the loop as the point at which to start again.

  There are two complications: (a) When CRLF is a valid newline sequence, and
  the current position is just before it, advance by an extra byte. (b)
  Otherwise we must ensure that we skip an entire UTF character if we are in
  UTF mode. */

  if (rc == PCRE2_ERROR_NOMATCH)
    {
    if (options == 0) break;                    /* All matches found */
    ovector[1] = start_offset + 1;              /* Advance one code unit */
    if (crlf_is_newline &&                      /* If CRLF is a newline & */
        start_offset < subject_length - 1 &&    /* we are at CRLF, */
        subject[start_offset] == '\r' &&
        subject[start_offset + 1] == '\n')
      ovector[1] += 1;                          /* Advance by one more. */
    else if (utf8)                              /* Otherwise, ensure we */
      {                                         /* advance a whole UTF-8 */
      while (ovector[1] < subject_length)       /* character. */
        {
        if ((subject[ovector[1]] & 0xc0) != 0x80) break;
        ovector[1] += 1;
        }
      }
    continue;    /* Go round the loop again */
    }

  /* Other matching errors are not recoverable. */

  if (rc < 0)
    {
    if (verbose == true) printf("Matching error %d\n", rc);
    pcre2_match_data_free(match_data);
    pcre2_code_free(re);
    str_free(f);
    return 1;
    }

  /* Match succeeded */
  if (!m) {
    column = calculate_correct_column((int)ovector[0]+1, subject);
    line = calculate_correct_line_from_column((int)ovector[0]+1, subject);
    f = get_upto_x_lines(line, subject);
    if (verbose == true) printf("Match succeeded again at offset %d\n", (int)ovector[0]);
    if (verbose == true) printf("%s\n%*c\n", f.string, column, '^');
    str_reset(f);
  }


  /* The match succeeded, but the output vector wasn't big enough. This
  should not happen. */

  if (rc == 0)
    if (verbose == true) printf("ovector was not big enough for all the captured substrings\n");

  /* We must guard against patterns such as /(?=.\K)/ that use \K in an
  assertion to set the start of a match later than its end. In this
  demonstration program, we just detect this case and give up. */

  if (ovector[0] > ovector[1])
    {
    if (verbose == true) printf("\\K was used in an assertion to set the match start after its end.\n"
      "From end to start the match was: %.*s\n", (int)(ovector[0] - ovector[1]),
        (char *)(subject + ovector[1]));
    if (verbose == true) printf("Run abandoned\n");
    pcre2_match_data_free(match_data);
    pcre2_code_free(re);
    str_free(f);
    return 1;
    }

  /* As before, show substrings stored in the output vector by number, and then
  also any named substrings. */

  for (i = 0; i < rc; i++)
    {
    PCRE2_SPTR substring_start = subject + ovector[2*i];
    size_t substring_length = ovector[2*i+1] - ovector[2*i];
    if (m) {
      str_new(match);
      for (int ii = 0; ii < (int)substring_length; ii++)
        str_insert_char(match, substring_start[ii]);
      matched_add((*m), strdup(match.string), (int)substring_length, ovector[2*i]);
      str_free(match);
    } else if (verbose == true) printf("%2d: %.*s\n", i, (int)substring_length, (char *)substring_start);
    }

  if (namecount != 0)
    {
    PCRE2_SPTR tabptr = name_table;
    if (verbose == true) printf("Named substrings\n");
    for (i = 0; i < namecount; i++)
      {
      int n = (tabptr[0] << 8) | tabptr[1];
      if (verbose == true) printf("(%d) %*s: %.*s\n", n, name_entry_size - 3, tabptr + 2,
        (int)(ovector[2*n+1] - ovector[2*n]), subject + ovector[2*n]);
      tabptr += name_entry_size;
      }
    }
  }      /* End of loop to find second and subsequent matches */

pcre2_match_data_free(match_data);
pcre2_code_free(re);
str_free(f);
return 0;
}

/* End of pcre2demo.c */


// Return to the PCRE2 index page.


#endif
int   yydebug = 0;
int   yylineNumber = 0;
#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
# define yyprintf(args)	{ if (yydebug) fprintf args; }
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __pos2;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getcharf();					\
    if (yy) yy->__pos2++;\
    if ('\n' == yyc || '\r' == yyc) ++yylineNumber;	\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0, 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getcharf();					\
    if (yyctx) yyctx->__pos2++;\
    if ('\n' == yyc || '\r' == yyc) ++yylineNumber;	\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchRegex(yycontext *yy, unsigned char *bits)
{
  str_new(save);
  str_new(save_prefix);
  str_new(save_);
  char * ch = malloc(2);
  ch[0] = 0; ch[1] = 0;
  int isempty = strcmp("", yy->__buf+yy->__pos);
  if (isempty) str_insert_string(save_prefix, yy->__buf+yy->__pos);
  while((ch[0] = getcharf()) != EOF) str_insert_string(save, ch);
  free(ch);
  if (save.len == 0) return 0;
  if (yydebug) printf("looked ahead to grab '%s' from YY_IN\n", save.json.string);
  if (isempty) str_insert_string(save_, save_prefix.string);
  str_insert_string(save_, save.string);
  char * string = strdup(save_.string);
  while(save.len) {
    ungetcf(save.string[save.len-1]);
    str_undo(save);
  }
  str_free(save);
  str_free(save_prefix);
  str_free(save_);
  matched_new(m);
  int ret = 0;
  if (regex_verbose2(bits, string, 1, &m, false) != 1) {
    if (yydebug) matched_info(m);
    ret = 1;
    for (int i = 0; i < m->len; i++) yymatchDot(yy);
  } else ret = 0;
  matched_free(m);
  free(string);
  yyprintf((stderr, "  %s yymatchRegex @ %s\n", ret==1?"ok":"fail", yy->__buf+yy->__pos));
  return ret;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_end_of_line(yycontext *yy); /* 24 */
YY_RULE(int) yy_comma(yycontext *yy); /* 23 */
YY_RULE(int) yy___(yycontext *yy); /* 22 */
YY_RULE(int) yy_tab(yycontext *yy); /* 21 */
YY_RULE(int) yy_space(yycontext *yy); /* 20 */
YY_RULE(int) yy_brackets(yycontext *yy); /* 19 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 18 */
YY_RULE(int) yy_quotes(yycontext *yy); /* 17 */
YY_RULE(int) yy_symbol(yycontext *yy); /* 16 */
YY_RULE(int) yy_number(yycontext *yy); /* 15 */
YY_RULE(int) yy_word(yycontext *yy); /* 14 */
YY_RULE(int) yy_single(yycontext *yy); /* 13 */
YY_RULE(int) yy_pair(yycontext *yy); /* 12 */
YY_RULE(int) yy_item(yycontext *yy); /* 11 */
YY_RULE(int) yy_ha_statement(yycontext *yy); /* 10 */
YY_RULE(int) yy__(yycontext *yy); /* 9 */
YY_RULE(int) yy_colon(yycontext *yy); /* 8 */
YY_RULE(int) yy_wordISA(yycontext *yy); /* 7 */
YY_RULE(int) yy_hash(yycontext *yy); /* 6 */
YY_RULE(int) yy_EOL(yycontext *yy); /* 5 */
YY_RULE(int) yy_ha2(yycontext *yy); /* 4 */
YY_RULE(int) yy_ha(yycontext *yy); /* 3 */
YY_RULE(int) yy_comment(yycontext *yy); /* 2 */
YY_RULE(int) yy_a(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_comment(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_comment\n"));
  {
   printf("comment = '%s'\n", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_comma(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_comma\n"));
  {
   puts("comma"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_brackets(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_brackets\n"));
  {
   printf("bracket = '%s'\n", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_EOF(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_EOF\n"));
  {
   printf("EOF\n"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_EOL(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_EOL\n"));
  {
   printf("EOL\n"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_quotes(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_quotes\n"));
  {
   printf("quotes = %s\n", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_symbol(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_symbol\n"));
  {
   printf("symbol = '%s'\n", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_number\n"));
  {
   printf("number = '%s'\n", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_word(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_word\n"));
  {
   printf("word = '%s' func = %s\n", yytext, __ISA_FUNCTION__); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_colon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_colon\n"));
  {
   printf("colon = %s\n", yytext) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_hash(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_hash\n"));
  {
   printf("hash = %s\n", yytext) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_pair(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pair\n"));
  {
   puts("pair");
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_single(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_single\n"));
  {
   puts("single");
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_item(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_item\n"));
  {
   puts("item");
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_ha2(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ha2\n"));
  {
   puts("hash number statement 2") ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ha2(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ha2\n"));
  {
   puts("hash number statement BEGIN") ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ha2(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ha2\n"));
  {
   ISA_FUNC_ASSIGN; ps(__ISA_FUNCTION__);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_ha(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ha\n"));
  {
   puts("hash number statement") ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ha(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ha\n"));
  {
   puts("hash number statement BEGIN") ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ha(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ha\n"));
  {
   ISA_FUNC_ASSIGN; ps(__ISA_FUNCTION__);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_a(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_a\n"));
  {
   puts("a");
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_end_of_line(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "end_of_line"));
  {
  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;
  if (!yymatchString(yy, "\r\n"))  {
  goto l3;
  }
  goto l2;
  l3:;
  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;
  if (!yymatchChar(yy, '\n'))  {
  goto l4;
  }
  goto l2;
  l4:;
  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;
  if (!yymatchChar(yy, '\r'))  {
  goto l1;
  }
  }
  l2:;
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_line", yy->__buf+yy->__pos));
  return 1;
  l1:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_line", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_comma(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "comma"));
  if (!yymatchChar(yy, ','))  {
  goto l5;
  }
  yyDo(yy, yy_1_comma, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "comma", yy->__buf+yy->__pos));
  return 1;
  l5:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comma", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy___(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "__"));
  l7:;
  {
  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;
  {
  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;
  if (!yymatchChar(yy, ' '))  {
  goto l10;
  }
  goto l9;
  l10:;
  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;
  if (!yymatchChar(yy, '\t'))  {
  goto l8;
  }
  }
  l9:;
  goto l7;
  l8:;
  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 1;
}

YY_RULE(int) yy_tab(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "tab"));
  if (!yymatchChar(yy, '\t'))  {
  goto l11;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "tab", yy->__buf+yy->__pos));
  return 1;
  l11:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "tab", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_space(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "space"));
  if (!yymatchChar(yy, ' '))  {
  goto l12;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yy->__buf+yy->__pos));
  return 1;
  l12:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_brackets(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "brackets"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l13;
#undef yytext
#undef yyleng
  }
  {
  int yypos14= yy->__pos, yythunkpos14= yy->__thunkpos;
  if (!yymatchChar(yy, '('))  {
  goto l15;
  }
  goto l14;
  l15:;
  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  if (!yymatchChar(yy, '['))  {
  goto l16;
  }
  goto l14;
  l16:;
  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  if (!yymatchChar(yy, '{'))  {
  goto l17;
  }
  goto l14;
  l17:;
  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  if (!yymatchChar(yy, ')'))  {
  goto l18;
  }
  goto l14;
  l18:;
  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  if (!yymatchChar(yy, ']'))  {
  goto l19;
  }
  goto l14;
  l19:;
  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  if (!yymatchChar(yy, '}'))  {
  goto l13;
  }
  }
  l14:;
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l13;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_brackets, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "brackets", yy->__buf+yy->__pos));
  return 1;
  l13:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "brackets", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_EOF(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {
  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;
  if (!yymatchDot(yy))   {
  goto l21;
  }
  goto l20;
  l21:;
  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;
  }
  yyDo(yy, yy_1_EOF, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l20:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_quotes(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "quotes"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l22;
#undef yytext
#undef yyleng
  }
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\204\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l22;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l22;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_quotes, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "quotes", yy->__buf+yy->__pos));
  return 1;
  l22:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "quotes", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_symbol(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "symbol"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l23;
#undef yytext
#undef yyleng
  }
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\110\304\000\054\000\000\000\020\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l23;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l23;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_symbol, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yy->__buf+yy->__pos));
  return 1;
  l23:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_number(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "number"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l24;
#undef yytext
#undef yyleng
  }
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l24;
  }
  l25:;
  {
  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l26;
  }
  goto l25;
  l26:;
  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l24;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_number, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "number", yy->__buf+yy->__pos));
  return 1;
  l24:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "number", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_word(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "word"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l27;
#undef yytext
#undef yyleng
  }
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l27;
  }
  l28:;
  {
  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l29;
  }
  goto l28;
  l29:;
  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l27;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_word, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "word", yy->__buf+yy->__pos));
  return 1;
  l27:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "word", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_single(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "single"));
  if (!yy_word(yy))   {
  goto l30;
  }
  yyDo(yy, yy_1_single, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "single", yy->__buf+yy->__pos));
  return 1;
  l30:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "single", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_pair(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pair"));
  if (!yy_word(yy))   {
  goto l31;
  }
  if (!yy_colon(yy))   {
  goto l31;
  }
  if (!yy_word(yy))   {
  goto l31;
  }
  yyDo(yy, yy_1_pair, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pair", yy->__buf+yy->__pos));
  return 1;
  l31:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pair", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_item(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "item"));
  if (!yy_word(yy))   {
  goto l32;
  }
  if (!yy_colon(yy))   {
  goto l32;
  }
  yyDo(yy, yy_1_item, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "item", yy->__buf+yy->__pos));
  return 1;
  l32:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "item", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_ha_statement(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ha_statement"));
  if (!yy__(yy))   {
  goto l33;
  }
  {
  int yypos34= yy->__pos, yythunkpos34= yy->__thunkpos;
  if (!yy_comment(yy))   {
  goto l35;
  }
  goto l34;
  l35:;
  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;
  if (!yy_item(yy))   {
  goto l36;
  }
  if (!yy__(yy))   {
  goto l36;
  }
  {
  int yypos37= yy->__pos, yythunkpos37= yy->__thunkpos;
  if (!yy_pair(yy))   {
  goto l38;
  }
  goto l37;
  l38:;
  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;
  if (!yy_single(yy))   {
  goto l36;
  }
  }
  l37:;
  if (!yy__(yy))   {
  goto l36;
  }
  {
  int yypos39= yy->__pos, yythunkpos39= yy->__thunkpos;
  if (!yy_comment(yy))   {
  goto l39;
  }
  goto l40;
  l39:;
  yy->__pos= yypos39; yy->__thunkpos= yythunkpos39;
  }
  l40:;
  goto l34;
  l36:;
  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;
  if (!yy_EOL(yy))   {
  goto l33;
  }
  }
  l34:;
  yyprintf((stderr, "  ok   %s @ %s\n", "ha_statement", yy->__buf+yy->__pos));
  return 1;
  l33:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ha_statement", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l42:;
  {
  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;
  {
  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;
  if (!yy_space(yy))   {
  goto l45;
  }
  goto l44;
  l45:;
  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;
  if (!yy_tab(yy))   {
  goto l43;
  }
  }
  l44:;
  goto l42;
  l43:;
  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}

YY_RULE(int) yy_colon(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "colon"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l46;
#undef yytext
#undef yyleng
  }
  if (!yymatchChar(yy, ':'))  {
  goto l46;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l46;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_colon, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "colon", yy->__buf+yy->__pos));
  return 1;
  l46:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "colon", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_wordISA(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "wordISA"));
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l47;
  }
  l48:;
  {
  int yypos49= yy->__pos, yythunkpos49= yy->__thunkpos;
  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"))  {
  goto l49;
  }
  goto l48;
  l49:;
  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "wordISA", yy->__buf+yy->__pos));
  return 1;
  l47:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wordISA", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_hash(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hash"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l50;
#undef yytext
#undef yyleng
  }
  if (!yymatchChar(yy, '#'))  {
  goto l50;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l50;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_hash, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "hash", yy->__buf+yy->__pos));
  return 1;
  l50:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hash", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_EOL(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l51;
#undef yytext
#undef yyleng
  }
  {
  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;
  if (!yymatchChar(yy, '\n'))  {
  goto l53;
  }
  goto l52;
  l53:;
  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  if (!yymatchString(yy, "\r\n"))  {
  goto l54;
  }
  goto l52;
  l54:;
  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  if (!yymatchChar(yy, '\r'))  {
  goto l55;
  }
  goto l52;
  l55:;
  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  if (!yymatchChar(yy, ';'))  {
  goto l51;
  }
  }
  l52:;
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l51;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_EOL, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 1;
  l51:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_ha2(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ha2"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l56;
#undef yytext
#undef yyleng
  }
  if (!yy_wordISA(yy))   {
  goto l56;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l56;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_ha2, yy->__begin, yy->__end);
  if (!yy_colon(yy))   {
  goto l56;
  }
  if (!yy_EOL(yy))   {
  goto l56;
  }
  yyDo(yy, yy_2_ha2, yy->__begin, yy->__end);
  if (!yy__(yy))   {
  goto l56;
  }
  if (!yy_ha_statement(yy))   {
  goto l56;
  }
  l57:;
  {
  int yypos58= yy->__pos, yythunkpos58= yy->__thunkpos;
  if (!yy_ha_statement(yy))   {
  goto l58;
  }
  goto l57;
  l58:;
  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;
  }
  yyDo(yy, yy_3_ha2, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ha2", yy->__buf+yy->__pos));
  return 1;
  l56:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ha2", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_ha(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ha"));
  if (!yy_hash(yy))   {
  goto l59;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l59;
#undef yytext
#undef yyleng
  }
  if (!yy_wordISA(yy))   {
  goto l59;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l59;
#undef yytext
#undef yyleng
  }
  yyDo(yy, yy_1_ha, yy->__begin, yy->__end);
  if (!yy_colon(yy))   {
  goto l59;
  }
  if (!yy_EOL(yy))   {
  goto l59;
  }
  yyDo(yy, yy_2_ha, yy->__begin, yy->__end);
  if (!yy__(yy))   {
  goto l59;
  }
  if (!yy_ha_statement(yy))   {
  goto l59;
  }
  l60:;
  {
  int yypos61= yy->__pos, yythunkpos61= yy->__thunkpos;
  if (!yy_ha_statement(yy))   {
  goto l61;
  }
  goto l60;
  l61:;
  yy->__pos= yypos61; yy->__thunkpos= yythunkpos61;
  }
  yyDo(yy, yy_3_ha, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ha", yy->__buf+yy->__pos));
  return 1;
  l59:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ha", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_comment(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "comment"));
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l62;
#undef yytext
#undef yyleng
  }
  if (!yymatchString(yy, "//"))  {
  goto l62;
  }
  l63:;
  {
  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;
  {
  int yypos65= yy->__pos, yythunkpos65= yy->__thunkpos;
  if (!yy_end_of_line(yy))   {
  goto l65;
  }
  goto l64;
  l65:;
  yy->__pos= yypos65; yy->__thunkpos= yythunkpos65;
  }
  if (!yymatchDot(yy))   {
  goto l64;
  }
  goto l63;
  l64:;
  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;
  }
  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l62;
#undef yytext
#undef yyleng
  }
  if (!yy_end_of_line(yy))   {
  goto l62;
  }
  yyDo(yy, yy_1_comment, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yy->__buf+yy->__pos));
  return 1;
  l62:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yy->__buf+yy->__pos));
  return 0;
}

YY_RULE(int) yy_a(yycontext *yy)
{
  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "a"));
  {
  int yypos69= yy->__pos, yythunkpos69= yy->__thunkpos;
  if (!yy_comment(yy))   {
  goto l70;
  }
  goto l69;
  l70:;
  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;
  if (!yy_ha(yy))   {
  goto l71;
  }
  goto l69;
  l71:;
  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;
  if (!yy_ha2(yy))   {
  goto l72;
  }
  goto l69;
  l72:;
  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;
  if (!yy_EOL(yy))   {
  goto l66;
  }
  }
  l69:;
  yyDo(yy, yy_1_a, yy->__begin, yy->__end);
  l67:;
  {
  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;
  {
  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;
  if (!yy_comment(yy))   {
  goto l74;
  }
  goto l73;
  l74:;
  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;
  if (!yy_ha(yy))   {
  goto l75;
  }
  goto l73;
  l75:;
  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;
  if (!yy_ha2(yy))   {
  goto l76;
  }
  goto l73;
  l76:;
  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;
  if (!yy_EOL(yy))   {
  goto l68;
  }
  }
  l73:;
  yyDo(yy, yy_1_a, yy->__begin, yy->__end);
  goto l67;
  l68:;
  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "a", yy->__buf+yy->__pos));
  return 1;
  l66:;
  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "a", yy->__buf+yy->__pos));
  return 0;
}


#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_a);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
void yyparse__(YY_CTX_PARAM_ char * in) {
	if (in == NULL) {
		yyfrom_FILE = true;
	}
	else {
		yyfrom_FILE = false;
		yy_FILE_string_pos = 0;
		yy_FILE_string = in;
	}
	while (yyparse(YY_CTX_ARG));
}
void yyparse__x(char * in, YY_CTX_PARAM_ yyrule yystart) {
	if (in == NULL) {
		yyfrom_FILE = true;
	}
	else {
		yyfrom_FILE = false;
		yy_FILE_string_pos = 0;
		yy_FILE_string = in;
	}
	while (YYPARSEFROM(YY_CTX_ARG_ yystart));
}

int main(int argc, char **argv)
{
	if (argc > 1) {
		if (!(yy_FILE_file = fopen(argv[1], "r"))) {
			perror(argv[1]);
			exit(1);
		}
		while (yyparse());
	    fclose(yy_FILE_file);
	}
	return 0;
}

